# Default target: dev. CI uses staging (staging/temp); CD uses prod.
# Project/dataset/keyfile use env_var so CI/CD can inject; defaults support local dev.
# Python models (e.g. is_holiday_2025) need compute_region and gcs_bucket — set DBT_GCS_BUCKET for local runs.
default:
  target: dev
  outputs:
    dev:
      type: bigquery
      threads: 4
      method: service-account
      keyfile: "{{ env_var('DBT_KEYFILE_DEV') }}"
      project: "{{ env_var('DBT_BQ_PROJECT_DEV') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET_DEV') }}"
      location: US
      # compute_region: "{{ env_var('DBT_COMPUTE_REGION', 'US') }}"
      # gcs_bucket: "{{ env_var('DBT_GCS_BUCKET', 'data-platforms-team-sandbox-dbt-python') }}"
      
    # Staging/temp — same project as dev, different dataset only. Used by CI for dbt compile + dbt test.
    # staging:
    #  type: bigquery
    #  threads: 4
    #  method: service-account
    #  keyfile: "{{ env_var('DBT_KEYFILE_DEV', '/Users/gaurav/Downloads/Service-Account/data-platforms-team-sandbox-dbt.json') }}"
    #  project: "{{ env_var('DBT_BQ_PROJECT_DEV') }}"
    #  dataset: "{{ env_var('DBT_BQ_DATASET_DEV') }}"
    #  location: US
      # compute_region: "{{ env_var('DBT_COMPUTE_REGION', 'US') }}"
      # gcs_bucket: "{{ env_var('DBT_GCS_BUCKET', 'data-platforms-team-sandbox-dbt-python') }}"
      ### prod   '/Users/gaurav/Downloads/Service-Account/data-platforms-team-sandbox-84c16172b233.json'

    prod:
      type: bigquery
      threads: 4
      method: service-account
      keyfile: "{{ env_var('DBT_KEYFILE_PROD') }}"
      project: "{{ env_var('DBT_BQ_PROJECT_PROD') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET_PROD') }}"
      location: US
      # compute_region: "{{ env_var('DBT_COMPUTE_REGION', 'US') }}"
      # gcs_bucket: "{{ env_var('DBT_GCS_BUCKET', 'data-platforms-team-sandbox-dbt-python') }}"
