# Default target: dev (OAuth). CI uses staging (service-account). CD uses prod (service-account).
# Dev: use gcloud auth application-default login; no keyfile. Staging/prod: service-account keyfile.
default:
  target: dev
  outputs:
    # Dev: OAuth via gcloud (no keyfile). Run: gcloud auth application-default login
    dev:
      type: bigquery
      threads: 4
      method: oauth
      project: "{{ env_var('DBT_BQ_PROJECT_DEV', 'data-platforms-team-sandbox') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET_DEV', 'dbt_gpoojary') }}"
      location: US

    # Staging: service-account (for CI). Same project as dev, different dataset.
    staging:
      type: bigquery
      threads: 4
      method: service-account
      keyfile: "{{ env_var('DBT_KEYFILE_DEV') }}"
      project: "{{ env_var('DBT_BQ_PROJECT_DEV') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET_DEV') }}"
      location: US

    # Prod: service-account (for CD)
    prod:
      type: bigquery
      threads: 4
      method: service-account
      keyfile: "{{ env_var('DBT_KEYFILE_PROD') }}"
      project: "{{ env_var('DBT_BQ_PROJECT_PROD') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET_PROD') }}"
      location: US
      # compute_region: "{{ env_var('DBT_COMPUTE_REGION', 'US') }}"
      # gcs_bucket: "{{ env_var('DBT_GCS_BUCKET', 'data-platforms-team-sandbox-dbt-python') }}"
